/* auto-generated by scripts/scan-outfits.mjs — do not edit */
export type OutfitTab = "soft" | "playful" | "afterdark";

export type OutfitPreset = {
  id: string;
  tab: OutfitTab;
  label: string;
  imageUrl: string;
};

/** Empty until you run `node scripts/scan-outfits.mjs` in the app repo. */
export const OUTFIT_PRESETS: OutfitPreset[] = [];
