import fs from "fs";
import path from "path";

const ROOT = path.join(process.cwd(), "public", "outfits");
const TABS = ["soft", "playful", "afterdark"];
const EXT = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"]);

function labelFromFile(name) {
  return name
    .replace(/\.[^.]+$/, "")
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

const presets = [];

for (const tab of TABS) {
  const dir = path.join(ROOT, tab);
  if (!fs.existsSync(dir)) {
    console.warn(`skip missing folder: public/outfits/${tab}`);
    continue;
  }

  const files = fs
    .readdirSync(dir)
    .filter((file) => EXT.has(path.extname(file).toLowerCase()))
    .sort((a, b) => a.localeCompare(b));

  for (const file of files) {
    const stem = file.replace(/\.[^.]+$/, "");
    presets.push({
      id: `${tab}-${stem}`,
      tab,
      label: labelFromFile(file),
      imageUrl: `/outfits/${tab}/${file}`,
    });
  }
}

const outDir = path.join(process.cwd(), "src", "outfits");
fs.mkdirSync(outDir, { recursive: true });

const jsonPath = path.join(outDir, "presets.generated.json");
const tsPath = path.join(outDir, "presets.generated.ts");

fs.writeFileSync(jsonPath, JSON.stringify(presets, null, 2) + "\n");
fs.writeFileSync(
  tsPath,
  `/* auto-generated by scripts/scan-outfits.mjs — do not edit */
export type OutfitTab = "soft" | "playful" | "afterdark";

export type OutfitPreset = {
  id: string;
  tab: OutfitTab;
  label: string;
  imageUrl: string;
};

export const OUTFIT_PRESETS: OutfitPreset[] = ${JSON.stringify(presets, null, 2)};
`
);

console.log(`Wrote ${presets.length} outfit presets → src/outfits/presets.generated.ts`);
